development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: "<%= ENV['DATABASE_NAME'] || 'journalduhacker_dev' %>"
  pool: 5
  username: "<%= ENV['DATABASE_USER'] %>"
  password: "<%= ENV['DATABASE_PASSWORD'] %>"
  host: "<%= ENV['DATABASE_HOST'] || 'db' %>"
  port: <%= ENV['DATABASE_PORT'] || 3306 %>

test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: "<%= ENV['DATABASE_NAME'] || 'journalduhacker_test' %>"
  pool: 5
  username: "<%= ENV['DATABASE_USER'] %>"
  password: "<%= ENV['DATABASE_PASSWORD'] %>"
  host: "<%= ENV['DATABASE_HOST'] || 'db' %>"
  port: <%= ENV['DATABASE_PORT'] || 3306 %>
  # Performance optimizations for tests
  variables:
    innodb_flush_log_at_trx_commit: 2  # Don't flush to disk on every commit
    sync_binlog: 0                      # Don't sync binlog (tests only!)
    innodb_buffer_pool_size: 1G         # More memory for InnoDB

production:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: "<%= ENV['DATABASE_NAME'] || 'journalduhacker' %>"
  username: "<%= ENV['DATABASE_USER'] %>"
  password: "<%= ENV['DATABASE_PASSWORD'] %>"
  host: "<%= ENV['DATABASE_HOST'] || 'db' %>"
  port: <%= ENV['DATABASE_PORT'] || 3306 %>
