development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: journalduhacker_dev
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  port: <%= ENV['DATABASE_PORT'] || 3306 %>

test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: journalduhacker_test
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  port: <%= ENV['DATABASE_PORT'] || 3306 %>

production:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  port: <%= ENV['DATABASE_PORT'] || 3306 %>
